In [1]:
import pandas as pd

In [77]:




df = pd.read_csv("https://raw.githubusercontent.com/mcarob/csvPandasVideojuegos/main/pruebaGeneral.csv",delimiter=";")
df = df.drop('Unnamed: 0', axis=1)

In [78]:
list(df)

['Name',
 'Overview',
 'Platform',
 'Year_of_Release',
 'Genre',
 'Publisher',
 'Global_players',
 'Critic_Score',
 'User_Score',
 'Developer',
 'alcohol_reference',
 'animated_blood',
 'blood',
 'blood_and_gore',
 'cartoon_violence',
 'crude_humor',
 'drug_reference',
 'fantasy_violence',
 'intense_violence',
 'language',
 'lyrics',
 'mature_humor',
 'mild_blood',
 'mild_cartoon_violence',
 'mild_fantasy_violence',
 'mild_language',
 'mild_lyrics',
 'mild_suggestive_themes',
 'mild_violence',
 'no_descriptors',
 'nudity',
 'partial_nudity',
 'sexual_content',
 'sexual_themes',
 'simulated_gambling',
 'strong_janguage',
 'strong_sexual_content',
 'suggestive_themes',
 'use_of_alcohol',
 'use_of_drugs_and_alcohol',
 'violence',
 'esrb_rating']

In [79]:
subsetx=['alcohol_reference',
 'animated_blood',
 'blood',
 'blood_and_gore',
 'cartoon_violence',
 'crude_humor',
 'drug_reference',
 'fantasy_violence',
 'intense_violence',
 'language',
 'lyrics',
 'mature_humor',
 'mild_blood',
 'mild_cartoon_violence',
 'mild_fantasy_violence',
 'mild_language',
 'mild_lyrics',
 'mild_suggestive_themes',
 'mild_violence',
 'no_descriptors',
 'nudity',
 'partial_nudity',
 'sexual_content',
 'sexual_themes',
 'simulated_gambling',
 'strong_janguage',
 'strong_sexual_content',
 'suggestive_themes',
 'use_of_alcohol',
 'use_of_drugs_and_alcohol',
 'violence']


In [80]:
dfaxisx=df[subsetx]

In [81]:
dfaxisx

alcohol_reference  animated_blood  blood  blood_and_gore  \
0                  0.0             0.0    0.0             1.0   
1                  0.0             0.0    0.0             1.0   
2                  0.0             0.0    0.0             1.0   
3                  0.0             0.0    0.0             1.0   
4                  0.0             0.0    1.0             0.0   
..                 ...             ...    ...             ...   
602                0.0             0.0    0.0             0.0   
603                0.0             0.0    0.0             0.0   
604                1.0             0.0    0.0             1.0   
605                0.0             0.0    1.0             0.0   
606                0.0             0.0    0.0             1.0   

     cartoon_violence  crude_humor  drug_reference  fantasy_violence  \
0                 0.0          0.0             0.0               0.0   
1                 0.0          0.0             0.0               0.0   
2                 0.0          0.0             1.0               0.0   
3                 0.0          0.0             1.0               0.0   
4                 0.0          0.0             0.0               0.0   
..                ...          ...             ...               ...   
602               0.0          0.0             0.0               0.0   
603               0.0          0.0             0.0               1.0   
604               0.0          0.0             0.0               0.0   
605               0.0          0.0             0.0               0.0   
606               0.0          0.0             0.0               0.0   

     intense_violence  language  ...  partial_nudity  sexual_content  \
0                 1.0       0.0  ...             0.0             0.0   
1                 1.0       0.0  ...             0.0             0.0   
2                 0.0       1.0  ...             0.0             0.0   
3                 0.0       1.0  ...             0.0             0.0   
4                 1.0       0.0  ...             0.0             0.0   
..                ...       ...  ...             ...             ...   
602               0.0       0.0  ...             0.0             0.0   
603               0.0       1.0  ...             0.0             0.0   
604               0.0       0.0  ...             0.0             0.0   
605               0.0       1.0  ...             0.0             0.0   
606               1.0       0.0  ...             0.0             0.0   

     sexual_themes  simulated_gambling  strong_janguage  \
0              0.0                 0.0              1.0   
1              0.0                 0.0              1.0   
2              0.0                 0.0              1.0   
3              0.0                 0.0              1.0   
4              0.0                 0.0              1.0   
..             ...                 ...              ...   
602            0.0                 0.0              0.0   
603            0.0                 0.0              0.0   
604            0.0                 0.0              0.0   
605            1.0                 1.0              1.0   
606            0.0                 0.0              1.0   

     strong_sexual_content  suggestive_themes  use_of_alcohol  \
0                      0.0                0.0             1.0   
1                      0.0                0.0             1.0   
2                      0.0                1.0             0.0   
3                      0.0                1.0             0.0   
4                      0.0                0.0             0.0   
..                     ...                ...             ...   
602                    0.0                0.0             0.0   
603                    0.0                0.0             0.0   
604                    0.0                0.0             0.0   
605                    0.0                0.0             0.0   
606                    0.0                0.0             1.0   

    

In [82]:
subsety=["esrb_rating"]


In [83]:
dfaxisy=df[subsety]

In [84]:
dfaxisy

esrb_rating
0             M
1             M
2             M
3             M
4             M
..          ...
602           E
603           T
604           T
605           M
606           M

[607 rows x 1 columns]

In [85]:
X=dfaxisx.to_numpy()

In [86]:
y=dfaxisy.to_numpy()

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [88]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [90]:

pca = PCA(n_components=4)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [91]:
classifier = RandomForestClassifier(max_depth=12, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

<ipython-input-91-e2b538cd42a4>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train, y_train)


In [92]:

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[29  0  0  0]
 [ 2 10  0  2]
 [ 0  0 48  0]
 [ 0  2  3 26]]
Accuracy0.9262295081967213


<ipython-input-30-bdd4ce6fafc6>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train, y_train)


[[ 0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0  0 11  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  3  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  6  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  5  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  4  0]
 [ 0 22  0  0  0  0  0  0  0  0  0  5  0]
 [ 0 25  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  9  0  0  0  0  0  0  0  0  0  2  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  9  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  4  0]]
Accuracy0.20398009950248755


In [93]:
persisitir=['Name',
 'Overview',
 'Platform',
 'Year_of_Release',
 'Genre',
 'Publisher',
 'Global_players',
 'Critic_Score',
 'User_Score',
 'Developer']



In [97]:
len(X_train[0])

4

In [96]:
len(X_test)

122

In [98]:
nuevoSet=[*X_train,*X_test]

In [99]:
len(nuevoSet)

607

list

x
